-- ============================================================================
-- v48_assassin_bombgoblin_balance.sql
--
-- Balance changes to Warfront fantasy units:
--
--   Assassin nerf:
--     hp 53 → 74  (+1.4×, makes it tankier but adds flying vulnerability)
--     new trait: takes 2× damage from flying units (flyingVulnMult = 2)
--     Rationale: assassin was too effective vs fragile backlines with no
--     counter-play; flying units (angel, harpy, phoenix, stormdrake) now
--     provide meaningful answers to a rushing assassin.
--
--   Bomb Goblin: no stat change here — the "explode on first contact" fix
--     is entirely client-side simulation logic; _warfront_score() uses
--     cost-weighted heuristics, not combat simulation.
--
-- Updates _warfront_units() so the server-side scoring function sees the
-- correct HP value for the assassin.
-- ============================================================================

create or replace function public._warfront_units()
returns jsonb language sql immutable as $$
select jsonb_build_array(
  jsonb_build_object('id','peasant','name','Peasant','icon','🧑','cost',1,'hp',56,'dmg',3,'spd',52,'atk_rate',1.4,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',1,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','footman','name','Footman','icon','🛡','cost',1,'hp',65,'dmg',6,'spd',43,'atk_rate',1.2,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',true,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','bombgoblin','name','Bomb Goblin','icon','💥','cost',1,'hp',43,'dmg',36,'spd',100,'atk_rate',999,'aoe',54,'lane','ground','melee',true,'ranged',false,'rusher',true,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',true,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',true,'collection','fantasy'),
  jsonb_build_object('id','archer','name','Archer','icon','🏹','cost',2,'hp',31,'dmg',8,'spd',41,'atk_rate',0.9,'aoe',0,'lane','ground','melee',false,'ranged',true,'rusher',false,'can_air',true,'prioritise_air',true,'engageR',151,'baseEngR',151,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',2,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',true,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','assassin','name','Assassin','icon','🗡','cost',2,'hp',74,'dmg',24,'spd',68,'atk_rate',1.4,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',true,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'flyingVulnMult',2,'collection','fantasy'),
  jsonb_build_object('id','shaman','name','Shaman','icon','✦','cost',2,'hp',44,'dmg',0,'spd',45,'atk_rate',999,'aoe',0,'lane','ground','melee',false,'ranged',true,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',200,'baseEngR',200,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',true,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','brute','name','Brute','icon','⚔','cost',3,'hp',111,'dmg',18,'spd',60,'atk_rate',0.9,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',true,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','cavalry','name','Cavalry','icon','🐴','cost',3,'hp',72,'dmg',29,'spd',63,'atk_rate',1.8,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',true,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',true,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','harpy','name','Harpy','displayName','Fairy','icon','🦅','cost',3,'hp',53,'dmg',9,'spd',89,'atk_rate',1.3,'aoe',0,'lane','air','melee',true,'ranged',false,'rusher',true,'can_air',true,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',0.5,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','troll','name','Troll','icon','👹','cost',3,'hp',156,'dmg',13,'spd',48,'atk_rate',1.3,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',3,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','voidwalker','name','Voidwalker','icon','👾','cost',3,'hp',97,'dmg',20,'spd',62,'atk_rate',1.1,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',5,'voidDur',1.5,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',true,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','frostwitch','name','Frost Witch','icon','❄','cost',4,'hp',109,'dmg',19,'spd',44,'atk_rate',1.6,'aoe',0,'lane','ground','melee',false,'ranged',true,'rusher',false,'can_air',true,'prioritise_air',false,'engageR',185,'baseEngR',185,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',2.0,'frostSlowPct',0.7,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','mage','name','Mage','icon','🔮','cost',4,'hp',48,'dmg',22,'spd',42,'atk_rate',1.6,'aoe',50,'lane','ground','melee',false,'ranged',true,'rusher',false,'can_air',true,'prioritise_air',true,'engageR',150,'baseEngR',150,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','mirrormage','name','Mirror Mage','icon','🪞','cost',4,'hp',96,'dmg',16,'spd',40,'atk_rate',1.5,'aoe',0,'lane','ground','melee',false,'ranged',true,'rusher',false,'can_air',true,'prioritise_air',false,'engageR',140,'baseEngR',140,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0.4,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'mirrorAll',true,'collection','fantasy'),
  jsonb_build_object('id','necromancer','name','Necromancer','icon','💀','cost',4,'hp',102,'dmg',21,'spd',35,'atk_rate',1.9,'aoe',0,'lane','ground','melee',false,'ranged',true,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',140,'baseEngR',140,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',true,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','phoenix','name','Phoenix','icon','🔥','cost',5,'hp',66,'dmg',18,'spd',66,'atk_rate',1.4,'aoe',40,'lane','air','melee',false,'ranged',true,'rusher',false,'can_air',true,'prioritise_air',false,'engageR',140,'baseEngR',140,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',true,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','warlord','name','Warlord','icon','👑','cost',5,'hp',152,'dmg',20,'spd',38,'atk_rate',1.1,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',true,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','siege','name','Siege Engine','icon','💣','cost',5,'hp',60,'dmg',41,'spd',27,'atk_rate',2.1,'aoe',62,'lane','ground','melee',false,'ranged',true,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',160,'baseEngR',160,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','stormdrake','name','Storm Drake','icon','🐲','cost',5,'hp',82,'dmg',19,'spd',70,'atk_rate',1.8,'aoe',0,'lane','air','melee',false,'ranged',true,'rusher',false,'can_air',true,'prioritise_air',false,'engageR',160,'baseEngR',160,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',3,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','lumberjack','name','Lumberjack','icon','🪓','cost',2,'hp',68,'dmg',12,'spd',65,'atk_rate',0.6,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'lumberjackAxe',true,'collection','fantasy'),
  jsonb_build_object('id','angel','name','Angel','icon','🪽','cost',2,'hp',55,'dmg',0,'spd',60,'atk_rate',999,'aoe',0,'lane','air','melee',false,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',200,'baseEngR',200,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'isAngel',true,'angelCooldown',2,'collection','fantasy'),
  jsonb_build_object('id','genie','name','Genie','icon','🧞','cost',5,'hp',163,'dmg',17,'spd',45,'atk_rate',1.3,'aoe',0,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','timewizard','name','Time Wizard','icon','⏳','cost',4,'hp',108,'dmg',15,'spd',36,'atk_rate',2.1,'aoe',0,'lane','ground','melee',false,'ranged',true,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',80,'baseEngR',80,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy'),
  jsonb_build_object('id','golem','name','Golem','icon','🗿','cost',6,'hp',354,'dmg',33,'spd',24,'atk_rate',2.0,'aoe',42,'lane','ground','melee',true,'ranged',false,'rusher',false,'can_air',false,'prioritise_air',false,'engageR',36,'baseEngR',36,'aoeShield',0,'regenPerSec',0,'healRange',0,'reflectPct',0,'slowDur',0,'airMult',1,'aoeResist',1,'chain',0,'voidCycle',0,'voidDur',0,'isSelf',false,'isPx',false,'isAss',false,'isShaman',false,'isNecro',false,'isWarlord',false,'isFootman',false,'isArcher',false,'isBrute',false,'isCav',false,'isVoid',false,'isGoblin',false,'collection','fantasy')
)::jsonb;
$$;

-- ============================================================================
-- Done.
-- ============================================================================
